[package]
name = "intervals"
version = "0.1.2"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2018"
license = "MIT"

[features]
serde_derive = ["serde"]

[dependencies]
num-traits = "0.2"
serde = { version = "1", features = ["derive"], optional = true }
